[package]
name = "aimdb-adapters"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Runtime adapters for AimDB - Tokio, Embassy, and other async runtime integrations"

[dependencies]
