//! Linker args + build-time station configuration (design 042 §8.2).
//!
//! With `MESH_CONFIG` pointing at a station profile (`station.toml`, written
//! by `aimdb join` — design 043 §4), the broker address, slot topics, and
//! station name are generated into `OUT_DIR/station_config.rs` and baked into
//! the firmware: `MESH_CONFIG=../station.toml cargo run --release` is
//! build → flash → live. With `MESH_CONFIG` unset, the generated file carries
//! the local docker-compose demo defaults, so the tier-1 demo stays
//! zero-setup.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rustc-link-arg-bins=--nmagic");
    println!("cargo:rustc-link-arg-bins=-Tlink.x");
    println!("cargo:rustc-link-arg-bins=-Tdefmt.x");

    println!("cargo:rerun-if-env-changed=MESH_CONFIG");

    let config = match env::var("MESH_CONFIG") {
        Ok(path) => {
            println!("cargo:rerun-if-changed={path}");
            mesh_station_config(&path)
        }
        Err(_) => local_demo_config(),
    };

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::write(out_dir.join("station_config.rs"), config).unwrap();
}

/// Local docker-compose demo defaults (tier 1 — no profile, no mesh).
/// The topics mirror the `TempKey::Gamma`/…`::Gamma` link addresses in
/// `weather-mesh-common`.
fn local_demo_config() -> String {
    station_config("192.168.1.3", 1883, None, None, "gamma", "sensors/gamma")
}

/// Configuration from the station profile at `path` (design 043 §4).
fn mesh_station_config(path: &str) -> String {
    let text = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("MESH_CONFIG: cannot read '{path}': {e}"));
    let profile: toml::Value = toml::from_str(&text)
        .unwrap_or_else(|e| panic!("MESH_CONFIG: '{path}' is not valid TOML: {e}"));

    let version = profile
        .get("profile_version")
        .and_then(|v| v.as_integer())
        .unwrap_or_else(|| panic!("MESH_CONFIG: '{path}' has no profile_version"));
    assert!(
        version == 1,
        "MESH_CONFIG: unsupported profile_version {version} (this firmware understands 1)"
    );

    let str_field = |table: &str, key: &str| -> &str {
        profile
            .get(table)
            .and_then(|t| t.get(key))
            .and_then(|v| v.as_str())
            .unwrap_or_else(|| panic!("MESH_CONFIG: '{path}' has no [{table}] {key}"))
    };

    let broker_url = str_field("broker", "url");
    // The Embassy MQTT client has no TLS yet (design 042 §8.1) — a profile for
    // the public broker (mqtts://) cannot work; only a plain-TCP broker (e.g.
    // the local demo one) is reachable until that lands.
    let rest = broker_url.strip_prefix("mqtt://").unwrap_or_else(|| {
        panic!(
            "MESH_CONFIG: broker URL '{broker_url}' is not mqtt:// — the Embassy \
             MQTT client has no TLS support yet (design 042 §8.1), so this \
             firmware can only target a plain-TCP broker"
        )
    });
    let authority = rest.split('/').next().unwrap_or(rest);
    let (host, port) = match authority.rsplit_once(':') {
        Some((host, port)) => (
            host,
            port.parse::<u16>()
                .unwrap_or_else(|_| panic!("MESH_CONFIG: invalid broker port in '{broker_url}'")),
        ),
        None => (authority, 1883),
    };

    let station_id = profile
        .get("station_id")
        .and_then(|v| v.as_str())
        .unwrap_or_else(|| panic!("MESH_CONFIG: '{path}' has no station_id"));
    let slot: u16 = station_id
        .strip_prefix("slot-")
        .and_then(|n| n.parse().ok())
        .unwrap_or_else(|| {
            panic!("MESH_CONFIG: station_id '{station_id}' is not of the form slot-<n>")
        });

    let name = str_field("app", "name");
    let credentials = Some((
        str_field("broker", "username"),
        str_field("broker", "password"),
    ));

    station_config(
        host,
        port,
        credentials,
        Some(slot),
        name,
        &format!("station/{slot}"),
    )
}

/// Render the generated `station_config.rs`. String values go through `{:?}`
/// so arbitrary profile content stays a valid Rust literal.
fn station_config(
    host: &str,
    port: u16,
    credentials: Option<(&str, &str)>,
    slot: Option<u16>,
    name: &str,
    topic_prefix: &str,
) -> String {
    let credential_const = |value: Option<&str>| match value {
        Some(v) => format!("Some({v:?})"),
        None => "None".to_string(),
    };
    let username = credential_const(credentials.map(|(u, _)| u));
    let password = credential_const(credentials.map(|(_, p)| p));
    let slot = match slot {
        Some(n) => format!("Some({n})"),
        None => "None".to_string(),
    };

    format!(
        "// Generated by build.rs — station configuration (design 042 §8.2).\n\
         // Source: $MESH_CONFIG station profile, or local demo defaults. Do not edit.\n\
         pub const MQTT_BROKER_HOST: &str = {host:?};\n\
         pub const MQTT_BROKER_PORT: u16 = {port};\n\
         /// Broker credential from the profile. Unused until the Embassy MQTT\n\
         /// client supports authentication + TLS (design 042 §8.1, WP7).\n\
         #[allow(dead_code)]\n\
         pub const MQTT_USERNAME: Option<&str> = {username};\n\
         #[allow(dead_code)]\n\
         pub const MQTT_PASSWORD: Option<&str> = {password};\n\
         /// Assigned mesh slot; `None` in the local demo.\n\
         pub const STATION_SLOT: Option<u16> = {slot};\n\
         pub const STATION_NAME: &str = {name:?};\n\
         pub const TEMPERATURE_TOPIC: &str = \"mqtt://{topic_prefix}/temperature\";\n\
         pub const HUMIDITY_TOPIC: &str = \"mqtt://{topic_prefix}/humidity\";\n\
         pub const DEW_POINT_TOPIC: &str = \"mqtt://{topic_prefix}/dew_point\";\n"
    )
}
