[package]
name = "aimdb-examples-shared"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Shared code for AimDB examples and demos"
publish = false

[features]
default = ["std"]
std = ["aimdb-core/std", "aimdb-executor/std"]
embassy-runtime = [
    "aimdb-core/embassy-runtime",
    "aimdb-executor/embassy-types",
    "dep:defmt",
]
tokio-runtime = ["std", "aimdb-core/tokio-runtime"]

[dependencies]
aimdb-core = { path = "../../aimdb-core", default-features = false }
aimdb-executor = { path = "../../aimdb-executor", default-features = false }
defmt = { version = "0.3", optional = true }
