//! Type-safe, bidirectional schema migration with compile-time chain validation.
//!
//! This module provides an Alembic-inspired migration system where every version
//! transition is a typed, bidirectional step between concrete Rust structs.
//!
//! # Architecture
//!
//! - [`MigrationStep`] — a single upgrade/downgrade between two concrete types
//! - [`MigrationChain`] — runtime dispatch generated by [`migration_chain!`] macro
//! - [`migration_chain!`] — declarative macro that validates the chain at compile time
//!
//! # How It Works
//!
//! Each schema version is a concrete Rust struct. Migration steps convert between
//! adjacent versions with full type safety — no raw JSON manipulation.
//!
//! The `migration_chain!` macro generates:
//! 1. **Const assertions** — version sequence validated at compile time
//! 2. **Type-checked dispatch** — compiler rejects mismatched type chains
//! 3. **`MigrationChain` impl** — runtime upgrade/downgrade with version detection
//!
//! # Example
//!
//! ```rust
//! extern crate alloc;
//!
//! use aimdb_data_contracts::{SchemaType, MigrationStep, MigrationChain, MigrationError};
//! use aimdb_data_contracts::migration_chain;
//! use serde::{Deserialize, Serialize};
//!
//! // v1 schema
//! #[derive(Clone, Debug, Serialize, Deserialize)]
//! struct SensorV1 {
//!     schema_version: u32,
//!     temp: f32,
//!     timestamp: u64,
//! }
//! impl SchemaType for SensorV1 {
//!     const NAME: &'static str = "sensor_v1";
//!     const VERSION: u32 = 1;
//! }
//!
//! // v2 schema (current)
//! #[derive(Clone, Debug, Serialize, Deserialize)]
//! struct Sensor {
//!     schema_version: u32,
//!     celsius: f32,
//!     timestamp: u64,
//! }
//! impl SchemaType for Sensor {
//!     const NAME: &'static str = "sensor";
//!     const VERSION: u32 = 2;
//! }
//!
//! // Migration step: v1 -> v2
//! struct SensorV1ToV2;
//! impl MigrationStep for SensorV1ToV2 {
//!     type Older = SensorV1;
//!     type Newer = Sensor;
//!     const FROM_VERSION: u32 = 1;
//!     const TO_VERSION: u32 = 2;
//!
//!     fn up(v1: SensorV1) -> Result<Sensor, MigrationError> {
//!         Ok(Sensor { schema_version: 2, celsius: v1.temp, timestamp: v1.timestamp })
//!     }
//!     fn down(v2: Sensor) -> Result<SensorV1, MigrationError> {
//!         Ok(SensorV1 { schema_version: 1, temp: v2.celsius, timestamp: v2.timestamp })
//!     }
//! }
//!
//! // Wire up the chain
//! migration_chain! {
//!     type Current = Sensor;
//!     version_field = "schema_version";
//!     steps {
//!         SensorV1ToV2: SensorV1 => Sensor,
//!     }
//! }
//!
//! // Upgrade from v1 bytes
//! let v1_json = r#"{"schema_version":1,"temp":22.5,"timestamp":100}"#;
//! let sensor = Sensor::migrate_from_bytes(v1_json.as_bytes()).unwrap();
//! assert_eq!(sensor.celsius, 22.5);
//!
//! // Downgrade to v1 bytes
//! let v1_bytes = sensor.migrate_to_version(1).unwrap();
//! let v1_roundtrip: serde_json::Value = serde_json::from_slice(&v1_bytes).unwrap();
//! assert_eq!(v1_roundtrip["temp"], 22.5);
//! ```

use crate::SchemaType;

/// Error returned when schema migration fails.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum MigrationError {
    /// The source version is newer than this binary supports
    VersionTooNew { source: u32, current: u32 },
    /// The target downgrade version is below the minimum supported
    VersionTooOld { target: u32, minimum: u32 },
    /// Deserialization of a versioned payload failed
    DeserializationFailed(&'static str),
    /// Serialization during downgrade failed
    SerializationFailed(&'static str),
    /// A domain-specific conversion error in a MigrationStep
    ConversionFailed(&'static str),
    /// Payload is missing the version field
    MissingVersion,
}

impl core::fmt::Display for MigrationError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::VersionTooNew { source, current } => {
                write!(
                    f,
                    "source version {} is newer than current {}",
                    source, current
                )
            }
            Self::VersionTooOld { target, minimum } => {
                write!(
                    f,
                    "target version {} is below minimum supported {}",
                    target, minimum
                )
            }
            Self::DeserializationFailed(msg) => write!(f, "deserialization failed: {}", msg),
            Self::SerializationFailed(msg) => write!(f, "serialization failed: {}", msg),
            Self::ConversionFailed(msg) => write!(f, "conversion failed: {}", msg),
            Self::MissingVersion => write!(f, "payload missing version field"),
        }
    }
}

/// A single, typed, bidirectional migration step between two schema versions.
///
/// Each step converts between two concrete Rust types with full type safety.
/// The compiler enforces that `up()` and `down()` operate on the correct types.
///
/// # Example
///
/// ```rust,ignore
/// struct TemperatureV1ToV2;
/// impl MigrationStep for TemperatureV1ToV2 {
///     type Older = TemperatureV1;
///     type Newer = TemperatureV2;
///     const FROM_VERSION: u32 = 1;
///     const TO_VERSION: u32 = 2;
///
///     fn up(v1: TemperatureV1) -> Result<TemperatureV2, MigrationError> {
///         let celsius = match v1.unit.as_str() {
///             "F" => (v1.temp - 32.0) * 5.0 / 9.0,
///             "K" => v1.temp - 273.15,
///             _ => v1.temp,
///         };
///         Ok(TemperatureV2 { schema_version: 2, celsius, timestamp: v1.timestamp })
///     }
///     fn down(v2: TemperatureV2) -> Result<TemperatureV1, MigrationError> {
///         Ok(TemperatureV1 { schema_version: 1, temp: v2.celsius, timestamp: v2.timestamp, unit: "C".into() })
///     }
/// }
/// ```
pub trait MigrationStep {
    /// The older schema type (input to `up`, output of `down`)
    type Older;
    /// The newer schema type (output of `up`, input to `down`)
    type Newer;
    /// The version number of the Older type
    const FROM_VERSION: u32;
    /// The version number of the Newer type
    const TO_VERSION: u32;

    /// Upgrade: convert from older to newer representation.
    fn up(older: Self::Older) -> Result<Self::Newer, MigrationError>;
    /// Downgrade: convert from newer to older representation.
    fn down(newer: Self::Newer) -> Result<Self::Older, MigrationError>;
}

/// A complete, validated migration chain for a schema type.
///
/// Generated by the [`migration_chain!`] macro. Provides runtime dispatch
/// for upgrading from any historical version to the current version,
/// and downgrading from the current version to any historical version.
///
/// All chain validation (sequential versions, type chaining) happens
/// at compile time via const assertions and type checking in the macro expansion.
pub trait MigrationChain: SchemaType + serde::de::DeserializeOwned + serde::Serialize {
    /// The minimum version this chain can upgrade from.
    const MIN_VERSION: u32;

    /// Deserialize from bytes, auto-detecting version and upgrading to current.
    ///
    /// Reads the version field from the JSON payload and walks the migration
    /// chain upward to produce the current schema version.
    fn migrate_from_bytes(data: &[u8]) -> Result<Self, MigrationError>;

    /// Downgrade to a target version and serialize to bytes.
    ///
    /// Walks the migration chain downward from the current version to produce
    /// the serialized representation of an older schema version.
    fn migrate_to_version(
        &self,
        target_version: u32,
    ) -> Result<alloc::vec::Vec<u8>, MigrationError>;
}

// ═══════════════════════════════════════════════════════════════════
// MIGRATION CHAIN MACRO
// ═══════════════════════════════════════════════════════════════════

/// Validate the migration chain at compile time and generate `MigrationChain` impl.
///
/// # Syntax
///
/// ```rust,ignore
/// migration_chain! {
///     type Current = MyType;
///     version_field = "schema_version";
///     steps {
///         StepV1ToV2: TypeV1 => TypeV2,
///         StepV2ToV3: TypeV2 => MyType,
///     }
/// }
/// ```
///
/// # What it generates
///
/// 1. Const assertions validating version sequence and chain continuity
/// 2. `impl MigrationChain for Current` with upgrade/downgrade dispatch
/// 3. Type-checked match arms (compiler rejects broken chains)
#[macro_export]
macro_rules! migration_chain {
    // ── Single-step chain ──────────────────────────────────────────
    (
        type Current = $current:ty;
        version_field = $version_field:literal;
        steps {
            $step1:ty : $older1:ty => $newer1:ty $(,)?
        }
    ) => {
        // Compile-time validation
        const _: () = {
            // Step must increment by exactly 1
            assert!(
                <$step1 as $crate::MigrationStep>::TO_VERSION
                    == <$step1 as $crate::MigrationStep>::FROM_VERSION + 1,
                "migration step must increment version by exactly 1"
            );
            // First step starts at version 1
            assert!(
                <$step1 as $crate::MigrationStep>::FROM_VERSION == 1,
                "first migration step must start at version 1"
            );
            // Last step ends at current VERSION
            assert!(
                <$step1 as $crate::MigrationStep>::TO_VERSION
                    == <$current as $crate::SchemaType>::VERSION,
                "last migration step must end at current VERSION"
            );
        };

        impl $crate::MigrationChain for $current {
            const MIN_VERSION: u32 = 1;

            fn migrate_from_bytes(data: &[u8]) -> Result<Self, $crate::MigrationError> {
                let raw: serde_json::Value = serde_json::from_slice(data)
                    .map_err(|_| $crate::MigrationError::DeserializationFailed("invalid JSON"))?;

                let version = raw
                    .get($version_field)
                    .and_then(|v| v.as_u64())
                    .ok_or($crate::MigrationError::MissingVersion)? as u32;

                if version > <$current as $crate::SchemaType>::VERSION {
                    return Err($crate::MigrationError::VersionTooNew {
                        source: version,
                        current: <$current as $crate::SchemaType>::VERSION,
                    });
                }

                match version {
                    1 => {
                        let older: $older1 = serde_json::from_value(raw).map_err(|_| {
                            $crate::MigrationError::DeserializationFailed(concat!(
                                "failed to parse as ",
                                stringify!($older1)
                            ))
                        })?;
                        <$step1 as $crate::MigrationStep>::up(older)
                    }
                    v if v == <$current as $crate::SchemaType>::VERSION => {
                        serde_json::from_value(raw).map_err(|_| {
                            $crate::MigrationError::DeserializationFailed(concat!(
                                "failed to parse as ",
                                stringify!($current)
                            ))
                        })
                    }
                    _ => Err($crate::MigrationError::VersionTooNew {
                        source: version,
                        current: <$current as $crate::SchemaType>::VERSION,
                    }),
                }
            }

            fn migrate_to_version(
                &self,
                target_version: u32,
            ) -> Result<alloc::vec::Vec<u8>, $crate::MigrationError> {
                if target_version < Self::MIN_VERSION {
                    return Err($crate::MigrationError::VersionTooOld {
                        target: target_version,
                        minimum: Self::MIN_VERSION,
                    });
                }
                if target_version > <$current as $crate::SchemaType>::VERSION {
                    return Err($crate::MigrationError::VersionTooNew {
                        source: target_version,
                        current: <$current as $crate::SchemaType>::VERSION,
                    });
                }

                match target_version {
                    1 => {
                        let older = <$step1 as $crate::MigrationStep>::down(self.clone())?;
                        serde_json::to_vec(&older).map_err(|_| {
                            $crate::MigrationError::SerializationFailed(concat!(
                                "failed to serialize as ",
                                stringify!($older1)
                            ))
                        })
                    }
                    v if v == <$current as $crate::SchemaType>::VERSION => serde_json::to_vec(self)
                        .map_err(|_| {
                            $crate::MigrationError::SerializationFailed(concat!(
                                "failed to serialize as ",
                                stringify!($current)
                            ))
                        }),
                    _ => unreachable!(),
                }
            }
        }
    };

    // ── Two-step chain ─────────────────────────────────────────────
    (
        type Current = $current:ty;
        version_field = $version_field:literal;
        steps {
            $step1:ty : $older1:ty => $newer1:ty,
            $step2:ty : $older2:ty => $newer2:ty $(,)?
        }
    ) => {
        const _: () = {
            // Each step increments by exactly 1
            assert!(
                <$step1 as $crate::MigrationStep>::TO_VERSION
                    == <$step1 as $crate::MigrationStep>::FROM_VERSION + 1,
                "migration step must increment version by exactly 1"
            );
            assert!(
                <$step2 as $crate::MigrationStep>::TO_VERSION
                    == <$step2 as $crate::MigrationStep>::FROM_VERSION + 1,
                "migration step must increment version by exactly 1"
            );
            // First step starts at 1
            assert!(
                <$step1 as $crate::MigrationStep>::FROM_VERSION == 1,
                "first migration step must start at version 1"
            );
            // Steps are sequential
            assert!(
                <$step1 as $crate::MigrationStep>::TO_VERSION
                    == <$step2 as $crate::MigrationStep>::FROM_VERSION,
                "migration steps must be sequential"
            );
            // Last step ends at current VERSION
            assert!(
                <$step2 as $crate::MigrationStep>::TO_VERSION
                    == <$current as $crate::SchemaType>::VERSION,
                "last migration step must end at current VERSION"
            );
        };

        impl $crate::MigrationChain for $current {
            const MIN_VERSION: u32 = 1;

            fn migrate_from_bytes(data: &[u8]) -> Result<Self, $crate::MigrationError> {
                let raw: serde_json::Value = serde_json::from_slice(data)
                    .map_err(|_| $crate::MigrationError::DeserializationFailed("invalid JSON"))?;

                let version = raw
                    .get($version_field)
                    .and_then(|v| v.as_u64())
                    .ok_or($crate::MigrationError::MissingVersion)? as u32;

                if version > <$current as $crate::SchemaType>::VERSION {
                    return Err($crate::MigrationError::VersionTooNew {
                        source: version,
                        current: <$current as $crate::SchemaType>::VERSION,
                    });
                }

                match version {
                    1 => {
                        let v1: $older1 = serde_json::from_value(raw).map_err(|_| {
                            $crate::MigrationError::DeserializationFailed(concat!(
                                "failed to parse as ",
                                stringify!($older1)
                            ))
                        })?;
                        let v2 = <$step1 as $crate::MigrationStep>::up(v1)?;
                        <$step2 as $crate::MigrationStep>::up(v2)
                    }
                    2 => {
                        let v2: $older2 = serde_json::from_value(raw).map_err(|_| {
                            $crate::MigrationError::DeserializationFailed(concat!(
                                "failed to parse as ",
                                stringify!($older2)
                            ))
                        })?;
                        <$step2 as $crate::MigrationStep>::up(v2)
                    }
                    v if v == <$current as $crate::SchemaType>::VERSION => {
                        serde_json::from_value(raw).map_err(|_| {
                            $crate::MigrationError::DeserializationFailed(concat!(
                                "failed to parse as ",
                                stringify!($current)
                            ))
                        })
                    }
                    _ => Err($crate::MigrationError::VersionTooNew {
                        source: version,
                        current: <$current as $crate::SchemaType>::VERSION,
                    }),
                }
            }

            fn migrate_to_version(
                &self,
                target_version: u32,
            ) -> Result<alloc::vec::Vec<u8>, $crate::MigrationError> {
                if target_version < Self::MIN_VERSION {
                    return Err($crate::MigrationError::VersionTooOld {
                        target: target_version,
                        minimum: Self::MIN_VERSION,
                    });
                }
                if target_version > <$current as $crate::SchemaType>::VERSION {
                    return Err($crate::MigrationError::VersionTooNew {
                        source: target_version,
                        current: <$current as $crate::SchemaType>::VERSION,
                    });
                }

                match target_version {
                    1 => {
                        let v2 = <$step2 as $crate::MigrationStep>::down(self.clone())?;
                        let v1 = <$step1 as $crate::MigrationStep>::down(v2)?;
                        serde_json::to_vec(&v1).map_err(|_| {
                            $crate::MigrationError::SerializationFailed(concat!(
                                "failed to serialize as ",
                                stringify!($older1)
                            ))
                        })
                    }
                    2 => {
                        let v2 = <$step2 as $crate::MigrationStep>::down(self.clone())?;
                        serde_json::to_vec(&v2).map_err(|_| {
                            $crate::MigrationError::SerializationFailed(concat!(
                                "failed to serialize as ",
                                stringify!($older2)
                            ))
                        })
                    }
                    v if v == <$current as $crate::SchemaType>::VERSION => serde_json::to_vec(self)
                        .map_err(|_| {
                            $crate::MigrationError::SerializationFailed(concat!(
                                "failed to serialize as ",
                                stringify!($current)
                            ))
                        }),
                    _ => unreachable!(),
                }
            }
        }
    };

    // ── Three-step chain ───────────────────────────────────────────
    (
        type Current = $current:ty;
        version_field = $version_field:literal;
        steps {
            $step1:ty : $older1:ty => $newer1:ty,
            $step2:ty : $older2:ty => $newer2:ty,
            $step3:ty : $older3:ty => $newer3:ty $(,)?
        }
    ) => {
        const _: () = {
            assert!(
                <$step1 as $crate::MigrationStep>::TO_VERSION
                    == <$step1 as $crate::MigrationStep>::FROM_VERSION + 1,
                "migration step must increment version by exactly 1"
            );
            assert!(
                <$step2 as $crate::MigrationStep>::TO_VERSION
                    == <$step2 as $crate::MigrationStep>::FROM_VERSION + 1,
                "migration step must increment version by exactly 1"
            );
            assert!(
                <$step3 as $crate::MigrationStep>::TO_VERSION
                    == <$step3 as $crate::MigrationStep>::FROM_VERSION + 1,
                "migration step must increment version by exactly 1"
            );
            assert!(
                <$step1 as $crate::MigrationStep>::FROM_VERSION == 1,
                "first migration step must start at version 1"
            );
            assert!(
                <$step1 as $crate::MigrationStep>::TO_VERSION
                    == <$step2 as $crate::MigrationStep>::FROM_VERSION,
                "migration steps must be sequential"
            );
            assert!(
                <$step2 as $crate::MigrationStep>::TO_VERSION
                    == <$step3 as $crate::MigrationStep>::FROM_VERSION,
                "migration steps must be sequential"
            );
            assert!(
                <$step3 as $crate::MigrationStep>::TO_VERSION
                    == <$current as $crate::SchemaType>::VERSION,
                "last migration step must end at current VERSION"
            );
        };

        impl $crate::MigrationChain for $current {
            const MIN_VERSION: u32 = 1;

            fn migrate_from_bytes(data: &[u8]) -> Result<Self, $crate::MigrationError> {
                let raw: serde_json::Value = serde_json::from_slice(data)
                    .map_err(|_| $crate::MigrationError::DeserializationFailed("invalid JSON"))?;

                let version = raw
                    .get($version_field)
                    .and_then(|v| v.as_u64())
                    .ok_or($crate::MigrationError::MissingVersion)? as u32;

                if version > <$current as $crate::SchemaType>::VERSION {
                    return Err($crate::MigrationError::VersionTooNew {
                        source: version,
                        current: <$current as $crate::SchemaType>::VERSION,
                    });
                }

                match version {
                    1 => {
                        let v1: $older1 = serde_json::from_value(raw).map_err(|_| {
                            $crate::MigrationError::DeserializationFailed(concat!(
                                "failed to parse as ",
                                stringify!($older1)
                            ))
                        })?;
                        let v2 = <$step1 as $crate::MigrationStep>::up(v1)?;
                        let v3 = <$step2 as $crate::MigrationStep>::up(v2)?;
                        <$step3 as $crate::MigrationStep>::up(v3)
                    }
                    2 => {
                        let v2: $older2 = serde_json::from_value(raw).map_err(|_| {
                            $crate::MigrationError::DeserializationFailed(concat!(
                                "failed to parse as ",
                                stringify!($older2)
                            ))
                        })?;
                        let v3 = <$step2 as $crate::MigrationStep>::up(v2)?;
                        <$step3 as $crate::MigrationStep>::up(v3)
                    }
                    3 => {
                        let v3: $older3 = serde_json::from_value(raw).map_err(|_| {
                            $crate::MigrationError::DeserializationFailed(concat!(
                                "failed to parse as ",
                                stringify!($older3)
                            ))
                        })?;
                        <$step3 as $crate::MigrationStep>::up(v3)
                    }
                    v if v == <$current as $crate::SchemaType>::VERSION => {
                        serde_json::from_value(raw).map_err(|_| {
                            $crate::MigrationError::DeserializationFailed(concat!(
                                "failed to parse as ",
                                stringify!($current)
                            ))
                        })
                    }
                    _ => Err($crate::MigrationError::VersionTooNew {
                        source: version,
                        current: <$current as $crate::SchemaType>::VERSION,
                    }),
                }
            }

            fn migrate_to_version(
                &self,
                target_version: u32,
            ) -> Result<alloc::vec::Vec<u8>, $crate::MigrationError> {
                if target_version < Self::MIN_VERSION {
                    return Err($crate::MigrationError::VersionTooOld {
                        target: target_version,
                        minimum: Self::MIN_VERSION,
                    });
                }
                if target_version > <$current as $crate::SchemaType>::VERSION {
                    return Err($crate::MigrationError::VersionTooNew {
                        source: target_version,
                        current: <$current as $crate::SchemaType>::VERSION,
                    });
                }

                match target_version {
                    1 => {
                        let v3 = <$step3 as $crate::MigrationStep>::down(self.clone())?;
                        let v2 = <$step2 as $crate::MigrationStep>::down(v3)?;
                        let v1 = <$step1 as $crate::MigrationStep>::down(v2)?;
                        serde_json::to_vec(&v1).map_err(|_| {
                            $crate::MigrationError::SerializationFailed(concat!(
                                "failed to serialize as ",
                                stringify!($older1)
                            ))
                        })
                    }
                    2 => {
                        let v3 = <$step3 as $crate::MigrationStep>::down(self.clone())?;
                        let v2 = <$step2 as $crate::MigrationStep>::down(v3)?;
                        serde_json::to_vec(&v2).map_err(|_| {
                            $crate::MigrationError::SerializationFailed(concat!(
                                "failed to serialize as ",
                                stringify!($older2)
                            ))
                        })
                    }
                    3 => {
                        let v3 = <$step3 as $crate::MigrationStep>::down(self.clone())?;
                        serde_json::to_vec(&v3).map_err(|_| {
                            $crate::MigrationError::SerializationFailed(concat!(
                                "failed to serialize as ",
                                stringify!($older3)
                            ))
                        })
                    }
                    v if v == <$current as $crate::SchemaType>::VERSION => serde_json::to_vec(self)
                        .map_err(|_| {
                            $crate::MigrationError::SerializationFailed(concat!(
                                "failed to serialize as ",
                                stringify!($current)
                            ))
                        }),
                    _ => unreachable!(),
                }
            }
        }
    };
}
