[package]
name = "aimdb-connectors"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Protocol connectors for AimDB - MQTT, Kafka, DDS, and other communication bridges"

[dependencies]
